### ISSUE TITLE
On Android 6 Get Location return TimeOut Exception

### ISSUE THREAD

**Issue by andreadompe** [dpa99c/cordova-diagnostic-plugin-example#3] opened 2016-11-14 08:14 UTC
Dear dpa99c,
first of all thanks for your repository!
I've a problem about Android 6 Permission and geolocation,
when i try your example every request works perfectly, geolocation too (Request Location Authorization),
but when ii try to use the button Get Current Location i get timeout exception.
Please could you help me!

Best regards

Andrea

**Comment by dpa99c** [comment] 2016-11-16 19:18
The "Get Current Location" button just makes a call to the `navigator.geolocation.getCurrentPosition()` method of cordova-plugin-geolocation. 

What is your:
- device model
- Android version on device
- cordova-android platform version

**Comment by andreadompe** [comment] 2016-11-17 13:03
Device Model : Huawei P8 Lite
Android Version: 6.0
cordova-android: 5.0

If i restart the device it work correcly for a while, then it returning to say TimeOut Exception,
so i have to restart the device again.

I'm sure it's not a problem of your plugin, but i hope you could help me anyway.

Thanks a lot!

**Comment by dpa99c** [comment] 2016-11-17 17:11
Seems like there may be some device-specific issues with cordova-plugin-geolocation - [see here](https://github.com/driftyco/ng-cordova/issues/743).

If you have a different Android device, try on that. It works fine on my Samsung Galaxy S6.

But I'm closing this as the issue is not with the plugin or example project.

**Closed as completed by dpa99c** 2016-11-17 17:11 UTC
